#!/bin/bash
# (C) 2021 Peter Varkoly <pvarkoly@cephalix.eu> All rights reserved
source /etc/sysconfig/cranix || exit 1

IFS=","
for network in $( /usr/sbin/crx_api.sh GET system/enumerates/network | sed -e 's/\[//' -e 's/\]//' -e 's/"//g' )
do
	/usr/sbin/iptables -D FORWARD -s ${netowrk} -m limit --limit 10/minute  -p tcp -j LOG --log-prefix "NEW-CON "
done
